[project]
protostar-version = "0.8.1"
lib-path = "lib"

[contracts]
ChickenBondManager = ["src/ChickenBondManager.cairo"]
BLUSD = ["src/BLUSD.cairo"]
BondNFT = ["src/BondNFT.cairo"]
MockYearnVault = ["src/mock/MockYearnVault.cairo"]
MockLUSDToken = ["src/mock/MockLUSDToken.cairo"]
MockCurvePool = ["src/mock/MockCurvePool.cairo"]
