[project]
protostar-version = "0.9.0"
lib-path = "lib"
cairo-path = ["lib/cairo_contracts/src"]

[contracts]
ChickenBondManager = ["src/ChickenBondManager.cairo"]
BLUSD = ["src/BLUSD.cairo"]
LUSD = ["src/LUSD.cairo"]
BondNFT = ["src/BondNFT.cairo"]
MockYearnLUSDVault = ["src/mock/MockYearnLUSDVault.cairo"]
MockYearnCurveVault = ["src/mock/MockYearnCurveVault.cairo"]
MockLUSDToken = ["src/mock/MockLUSDToken.cairo"]
MockCurvePool = ["src/mock/MockCurvePool.cairo"]

